# Generated by Django 2.2.20 on 2022-03-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='价格')),
            ],
        ),
    ]
